language: objective-c

matrix:
  include:
    - {osx_image: xcode7.3, env: DST="name=iPhone 5"}
    - {osx_image: xcode7.3, env: DST="name=iPhone 5s"}
    - {osx_image: xcode8.3, env: DST="name=iPhone 5"}
    - {osx_image: xcode8.3, env: DST="name=iPhone 5s"}

script:
- xcodebuild test -scheme KVOExt -destination "$DST" 